{
  "title": "Your Failure is Your Fault",
  "date": "2020-07-27T11:29:03.000Z",
  "tags": [],
  "draft": false,
  "summary": "",
  "body": {
    "raw": "Last week, I announced the shut down of [Graphite Docs](<https://graphitedocs.com>), a company I had spent the last three-plus years working on. It was a hard decision, but it was one that was a long-time coming. While deciding to shut the company down was hard, what may have been even harder was coming to terms with the reason Graphite failed.\n\nWhen I first recognized Graphite's chances at success were waning, I wrote the problems off as something that would pass. It wasn't that I wasn't trying to correct the course, it was that I wasn't looking at the problems in the right light. And when you are trying to solve the wrong problems, you are only digging yourself deeper into a hole. As I grew closer and closer to what would be the end, I blamed external forces. I told my wife and my close friends that market conditions had hurt me, that cutting-edge tech was the problem, that blah blah blah.\n\nI was the problem, and that's ok. Every founder is the main problem their company faces. Those problems, though, can be turned into successes by accepting responsibility, changing course, and making sound decisions. Not many companies do this, not many founders do this. And that's why so many companies fail. Graphite's failure was not the result of any external forces beyond my control. It was squarely within my control, but I failed to execute.\n\nI won't enumerate the decisions I would revisit if given the opportunityâ€”that's for another post. Instead, I will use this post to illustrate to other founders that while it is easy to blame something else, someone else, the success and failure of your company is fully under your control. Are there times where a founder literally can't do anything to fix things? Sure, but those are rare. Much rarer than founder interviews would have you believe.\n\nThere is nothing wrong with making bad decisions, even if those bad decisions lead to the end of your company. Nothing wrong, unless of course, you don't learn from those bad decisions. Your failure is your fault, but it is also your opportunity. The opportunity to learn from failure is huge, and not recognizing it, not grasping it, squeezing every bit of knowledge you can out of it, is the true failure.\n\nJust remember, don't strive for failure. Strive to learn, knowing that failure is always a possibility. Don't hide from failure, don't find shame in it. Learn, adapt, move on. But acknowledge it.\n\n\n  \n",
    "code": "var Component=(()=>{var ur=Object.create;var I=Object.defineProperty;var lr=Object.getOwnPropertyDescriptor;var fr=Object.getOwnPropertyNames;var cr=Object.getPrototypeOf,dr=Object.prototype.hasOwnProperty;var z=(l,i)=>()=>(i||l((i={exports:{}}).exports,i),i.exports),br=(l,i)=>{for(var v in i)I(l,v,{get:i[v],enumerable:!0})},we=(l,i,v,_)=>{if(i&&typeof i==\"object\"||typeof i==\"function\")for(let y of fr(i))!dr.call(l,y)&&y!==v&&I(l,y,{get:()=>i[y],enumerable:!(_=lr(i,y))||_.enumerable});return l};var mr=(l,i,v)=>(v=l!=null?ur(cr(l)):{},we(i||!l||!l.__esModule?I(v,\"default\",{value:l,enumerable:!0}):v,l)),hr=l=>we(I({},\"__esModule\",{value:!0}),l);var Re=z((wr,Ee)=>{Ee.exports=React});var xe=z(q=>{\"use strict\";(function(){\"use strict\";var l=Re(),i=Symbol.for(\"react.element\"),v=Symbol.for(\"react.portal\"),_=Symbol.for(\"react.fragment\"),y=Symbol.for(\"react.strict_mode\"),X=Symbol.for(\"react.profiler\"),K=Symbol.for(\"react.provider\"),H=Symbol.for(\"react.context\"),j=Symbol.for(\"react.forward_ref\"),F=Symbol.for(\"react.suspense\"),A=Symbol.for(\"react.suspense_list\"),O=Symbol.for(\"react.memo\"),Y=Symbol.for(\"react.lazy\"),Oe=Symbol.for(\"react.offscreen\"),J=Symbol.iterator,Pe=\"@@iterator\";function Se(e){if(e===null||typeof e!=\"object\")return null;var r=J&&e[J]||e[Pe];return typeof r==\"function\"?r:null}var E=l.__SECRET_INTERNALS_DO_NOT_USE_OR_YOU_WILL_BE_FIRED;function d(e){{for(var r=arguments.length,t=new Array(r>1?r-1:0),n=1;n<r;n++)t[n-1]=arguments[n];De(\"error\",e,t)}}function De(e,r,t){{var n=E.ReactDebugCurrentFrame,s=n.getStackAddendum();s!==\"\"&&(r+=\"%s\",t=t.concat([s]));var u=t.map(function(o){return String(o)});u.unshift(\"Warning: \"+r),Function.prototype.apply.call(console[e],console,u)}}var ke=!1,Ne=!1,Ie=!1,Fe=!1,Ae=!1,Z;Z=Symbol.for(\"react.module.reference\");function Ye(e){return!!(typeof e==\"string\"||typeof e==\"function\"||e===_||e===X||Ae||e===y||e===F||e===A||Fe||e===Oe||ke||Ne||Ie||typeof e==\"object\"&&e!==null&&(e.$$typeof===Y||e.$$typeof===O||e.$$typeof===K||e.$$typeof===H||e.$$typeof===j||e.$$typeof===Z||e.getModuleId!==void 0))}function Ue(e,r,t){var n=e.displayName;if(n)return n;var s=r.displayName||r.name||\"\";return s!==\"\"?t+\"(\"+s+\")\":t}function Q(e){return e.displayName||\"Context\"}function p(e){if(e==null)return null;if(typeof e.tag==\"number\"&&d(\"Received an unexpected object in getComponentNameFromType(). This is likely a bug in React. Please file an issue.\"),typeof e==\"function\")return e.displayName||e.name||null;if(typeof e==\"string\")return e;switch(e){case _:return\"Fragment\";case v:return\"Portal\";case X:return\"Profiler\";case y:return\"StrictMode\";case F:return\"Suspense\";case A:return\"SuspenseList\"}if(typeof e==\"object\")switch(e.$$typeof){case H:var r=e;return Q(r)+\".Consumer\";case K:var t=e;return Q(t._context)+\".Provider\";case j:return Ue(e,e.render,\"ForwardRef\");case O:var n=e.displayName||null;return n!==null?n:p(e.type)||\"Memo\";case Y:{var s=e,u=s._payload,o=s._init;try{return p(o(u))}catch{return null}}}return null}var w=Object.assign,T=0,ee,re,te,ne,ae,oe,ie;function se(){}se.__reactDisabledLog=!0;function We(){{if(T===0){ee=console.log,re=console.info,te=console.warn,ne=console.error,ae=console.group,oe=console.groupCollapsed,ie=console.groupEnd;var e={configurable:!0,enumerable:!0,value:se,writable:!0};Object.defineProperties(console,{info:e,log:e,warn:e,error:e,group:e,groupCollapsed:e,groupEnd:e})}T++}}function $e(){{if(T--,T===0){var e={configurable:!0,enumerable:!0,writable:!0};Object.defineProperties(console,{log:w({},e,{value:ee}),info:w({},e,{value:re}),warn:w({},e,{value:te}),error:w({},e,{value:ne}),group:w({},e,{value:ae}),groupCollapsed:w({},e,{value:oe}),groupEnd:w({},e,{value:ie})})}T<0&&d(\"disabledDepth fell below zero. This is a bug in React. Please file an issue.\")}}var U=E.ReactCurrentDispatcher,W;function P(e,r,t){{if(W===void 0)try{throw Error()}catch(s){var n=s.stack.trim().match(/\\n( *(at )?)/);W=n&&n[1]||\"\"}return`\n`+W+e}}var $=!1,S;{var Me=typeof WeakMap==\"function\"?WeakMap:Map;S=new Me}function ue(e,r){if(!e||$)return\"\";{var t=S.get(e);if(t!==void 0)return t}var n;$=!0;var s=Error.prepareStackTrace;Error.prepareStackTrace=void 0;var u;u=U.current,U.current=null,We();try{if(r){var o=function(){throw Error()};if(Object.defineProperty(o.prototype,\"props\",{set:function(){throw Error()}}),typeof Reflect==\"object\"&&Reflect.construct){try{Reflect.construct(o,[])}catch(g){n=g}Reflect.construct(e,[],o)}else{try{o.call()}catch(g){n=g}e.call(o.prototype)}}else{try{throw Error()}catch(g){n=g}e()}}catch(g){if(g&&n&&typeof g.stack==\"string\"){for(var a=g.stack.split(`\n`),b=n.stack.split(`\n`),f=a.length-1,c=b.length-1;f>=1&&c>=0&&a[f]!==b[c];)c--;for(;f>=1&&c>=0;f--,c--)if(a[f]!==b[c]){if(f!==1||c!==1)do if(f--,c--,c<0||a[f]!==b[c]){var h=`\n`+a[f].replace(\" at new \",\" at \");return e.displayName&&h.includes(\"<anonymous>\")&&(h=h.replace(\"<anonymous>\",e.displayName)),typeof e==\"function\"&&S.set(e,h),h}while(f>=1&&c>=0);break}}}finally{$=!1,U.current=u,$e(),Error.prepareStackTrace=s}var x=e?e.displayName||e.name:\"\",_e=x?P(x):\"\";return typeof e==\"function\"&&S.set(e,_e),_e}function Ve(e,r,t){return ue(e,!1)}function Le(e){var r=e.prototype;return!!(r&&r.isReactComponent)}function D(e,r,t){if(e==null)return\"\";if(typeof e==\"function\")return ue(e,Le(e));if(typeof e==\"string\")return P(e);switch(e){case F:return P(\"Suspense\");case A:return P(\"SuspenseList\")}if(typeof e==\"object\")switch(e.$$typeof){case j:return Ve(e.render);case O:return D(e.type,r,t);case Y:{var n=e,s=n._payload,u=n._init;try{return D(u(s),r,t)}catch{}}}return\"\"}var k=Object.prototype.hasOwnProperty,le={},fe=E.ReactDebugCurrentFrame;function N(e){if(e){var r=e._owner,t=D(e.type,e._source,r?r.type:null);fe.setExtraStackFrame(t)}else fe.setExtraStackFrame(null)}function Ge(e,r,t,n,s){{var u=Function.call.bind(k);for(var o in e)if(u(e,o)){var a=void 0;try{if(typeof e[o]!=\"function\"){var b=Error((n||\"React class\")+\": \"+t+\" type `\"+o+\"` is invalid; it must be a function, usually from the `prop-types` package, but received `\"+typeof e[o]+\"`.This often happens because of typos such as `PropTypes.function` instead of `PropTypes.func`.\");throw b.name=\"Invariant Violation\",b}a=e[o](r,o,n,t,null,\"SECRET_DO_NOT_PASS_THIS_OR_YOU_WILL_BE_FIRED\")}catch(f){a=f}a&&!(a instanceof Error)&&(N(s),d(\"%s: type specification of %s `%s` is invalid; the type checker function must return `null` or an `Error` but returned a %s. You may have forgotten to pass an argument to the type checker creator (arrayOf, instanceOf, objectOf, oneOf, oneOfType, and shape all require an argument).\",n||\"React class\",t,o,typeof a),N(null)),a instanceof Error&&!(a.message in le)&&(le[a.message]=!0,N(s),d(\"Failed %s type: %s\",t,a.message),N(null))}}}var Be=Array.isArray;function M(e){return Be(e)}function ze(e){{var r=typeof Symbol==\"function\"&&Symbol.toStringTag,t=r&&e[Symbol.toStringTag]||e.constructor.name||\"Object\";return t}}function qe(e){try{return ce(e),!1}catch{return!0}}function ce(e){return\"\"+e}function de(e){if(qe(e))return d(\"The provided key is an unsupported type %s. This value must be coerced to a string before before using it here.\",ze(e)),ce(e)}var C=E.ReactCurrentOwner,Xe={key:!0,ref:!0,__self:!0,__source:!0},be,me,V;V={};function Ke(e){if(k.call(e,\"ref\")){var r=Object.getOwnPropertyDescriptor(e,\"ref\").get;if(r&&r.isReactWarning)return!1}return e.ref!==void 0}function He(e){if(k.call(e,\"key\")){var r=Object.getOwnPropertyDescriptor(e,\"key\").get;if(r&&r.isReactWarning)return!1}return e.key!==void 0}function Je(e,r){if(typeof e.ref==\"string\"&&C.current&&r&&C.current.stateNode!==r){var t=p(C.current.type);V[t]||(d('Component \"%s\" contains the string ref \"%s\". Support for string refs will be removed in a future major release. This case cannot be automatically converted to an arrow function. We ask you to manually fix this case by using useRef() or createRef() instead. Learn more about using refs safely here: https://reactjs.org/link/strict-mode-string-ref',p(C.current.type),e.ref),V[t]=!0)}}function Ze(e,r){{var t=function(){be||(be=!0,d(\"%s: `key` is not a prop. Trying to access it will result in `undefined` being returned. If you need to access the same value within the child component, you should pass it as a different prop. (https://reactjs.org/link/special-props)\",r))};t.isReactWarning=!0,Object.defineProperty(e,\"key\",{get:t,configurable:!0})}}function Qe(e,r){{var t=function(){me||(me=!0,d(\"%s: `ref` is not a prop. Trying to access it will result in `undefined` being returned. If you need to access the same value within the child component, you should pass it as a different prop. (https://reactjs.org/link/special-props)\",r))};t.isReactWarning=!0,Object.defineProperty(e,\"ref\",{get:t,configurable:!0})}}var er=function(e,r,t,n,s,u,o){var a={$$typeof:i,type:e,key:r,ref:t,props:o,_owner:u};return a._store={},Object.defineProperty(a._store,\"validated\",{configurable:!1,enumerable:!1,writable:!0,value:!1}),Object.defineProperty(a,\"_self\",{configurable:!1,enumerable:!1,writable:!1,value:n}),Object.defineProperty(a,\"_source\",{configurable:!1,enumerable:!1,writable:!1,value:s}),Object.freeze&&(Object.freeze(a.props),Object.freeze(a)),a};function rr(e,r,t,n,s){{var u,o={},a=null,b=null;t!==void 0&&(de(t),a=\"\"+t),He(r)&&(de(r.key),a=\"\"+r.key),Ke(r)&&(b=r.ref,Je(r,s));for(u in r)k.call(r,u)&&!Xe.hasOwnProperty(u)&&(o[u]=r[u]);if(e&&e.defaultProps){var f=e.defaultProps;for(u in f)o[u]===void 0&&(o[u]=f[u])}if(a||b){var c=typeof e==\"function\"?e.displayName||e.name||\"Unknown\":e;a&&Ze(o,c),b&&Qe(o,c)}return er(e,a,b,s,n,C.current,o)}}var L=E.ReactCurrentOwner,he=E.ReactDebugCurrentFrame;function R(e){if(e){var r=e._owner,t=D(e.type,e._source,r?r.type:null);he.setExtraStackFrame(t)}else he.setExtraStackFrame(null)}var G;G=!1;function B(e){return typeof e==\"object\"&&e!==null&&e.$$typeof===i}function ve(){{if(L.current){var e=p(L.current.type);if(e)return`\n\nCheck the render method of \\``+e+\"`.\"}return\"\"}}function tr(e){{if(e!==void 0){var r=e.fileName.replace(/^.*[\\\\\\/]/,\"\"),t=e.lineNumber;return`\n\nCheck your code at `+r+\":\"+t+\".\"}return\"\"}}var pe={};function nr(e){{var r=ve();if(!r){var t=typeof e==\"string\"?e:e.displayName||e.name;t&&(r=`\n\nCheck the top-level render call using <`+t+\">.\")}return r}}function ge(e,r){{if(!e._store||e._store.validated||e.key!=null)return;e._store.validated=!0;var t=nr(r);if(pe[t])return;pe[t]=!0;var n=\"\";e&&e._owner&&e._owner!==L.current&&(n=\" It was passed a child from \"+p(e._owner.type)+\".\"),R(e),d('Each child in a list should have a unique \"key\" prop.%s%s See https://reactjs.org/link/warning-keys for more information.',t,n),R(null)}}function ye(e,r){{if(typeof e!=\"object\")return;if(M(e))for(var t=0;t<e.length;t++){var n=e[t];B(n)&&ge(n,r)}else if(B(e))e._store&&(e._store.validated=!0);else if(e){var s=Se(e);if(typeof s==\"function\"&&s!==e.entries)for(var u=s.call(e),o;!(o=u.next()).done;)B(o.value)&&ge(o.value,r)}}}function ar(e){{var r=e.type;if(r==null||typeof r==\"string\")return;var t;if(typeof r==\"function\")t=r.propTypes;else if(typeof r==\"object\"&&(r.$$typeof===j||r.$$typeof===O))t=r.propTypes;else return;if(t){var n=p(r);Ge(t,e.props,\"prop\",n,e)}else if(r.PropTypes!==void 0&&!G){G=!0;var s=p(r);d(\"Component %s declared `PropTypes` instead of `propTypes`. Did you misspell the property assignment?\",s||\"Unknown\")}typeof r.getDefaultProps==\"function\"&&!r.getDefaultProps.isReactClassApproved&&d(\"getDefaultProps is only used on classic React.createClass definitions. Use a static property named `defaultProps` instead.\")}}function or(e){{for(var r=Object.keys(e.props),t=0;t<r.length;t++){var n=r[t];if(n!==\"children\"&&n!==\"key\"){R(e),d(\"Invalid prop `%s` supplied to `React.Fragment`. React.Fragment can only have `key` and `children` props.\",n),R(null);break}}e.ref!==null&&(R(e),d(\"Invalid attribute `ref` supplied to `React.Fragment`.\"),R(null))}}function ir(e,r,t,n,s,u){{var o=Ye(e);if(!o){var a=\"\";(e===void 0||typeof e==\"object\"&&e!==null&&Object.keys(e).length===0)&&(a+=\" You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.\");var b=tr(s);b?a+=b:a+=ve();var f;e===null?f=\"null\":M(e)?f=\"array\":e!==void 0&&e.$$typeof===i?(f=\"<\"+(p(e.type)||\"Unknown\")+\" />\",a=\" Did you accidentally export a JSX literal instead of a component?\"):f=typeof e,d(\"React.jsx: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: %s.%s\",f,a)}var c=rr(e,r,t,s,u);if(c==null)return c;if(o){var h=r.children;if(h!==void 0)if(n)if(M(h)){for(var x=0;x<h.length;x++)ye(h[x],e);Object.freeze&&Object.freeze(h)}else d(\"React.jsx: Static children should always be an array. You are likely explicitly calling React.jsxs or React.jsxDEV. Use the Babel transform instead.\");else ye(h,e)}return e===_?or(c):ar(c),c}}var sr=ir;q.Fragment=_,q.jsxDEV=sr})()});var Ce=z((Rr,Te)=>{\"use strict\";Te.exports=xe()});var yr={};br(yr,{default:()=>gr,frontmatter:()=>vr});var m=mr(Ce()),vr={slug:\"/your-failure-is-your-fault\",date:\"2020-07-27T11:29:03.000Z\",title:\"Your Failure is Your Fault\",tags:[],summary:\"\",draft:!1};function je(l){let i=Object.assign({p:\"p\",a:\"a\"},l.components);return(0,m.jsxDEV)(m.Fragment,{children:[(0,m.jsxDEV)(i.p,{children:[\"Last week, I announced the shut down of \",(0,m.jsxDEV)(i.a,{href:\"https://graphitedocs.com\",children:\"Graphite Docs\"},void 0,!1,{fileName:\"/Users/polluterofminds/Development/tailwind-nextjs-starter-blog/_mdx_bundler_entry_point-e5188e79-a369-42dd-b423-d109b2bcb5b7.mdx\",lineNumber:9,columnNumber:41},this),\", a company I had spent the last three-plus years working on. It was a hard decision, but it was one that was a long-time coming. While deciding to shut the company down was hard, what may have been even harder was coming to terms with the reason Graphite failed.\"]},void 0,!0,{fileName:\"/Users/polluterofminds/Development/tailwind-nextjs-starter-blog/_mdx_bundler_entry_point-e5188e79-a369-42dd-b423-d109b2bcb5b7.mdx\",lineNumber:9,columnNumber:1},this),(0,m.jsxDEV)(i.p,{children:\"When I first recognized Graphite's chances at success were waning, I wrote the problems off as something that would pass. It wasn't that I wasn't trying to correct the course, it was that I wasn't looking at the problems in the right light. And when you are trying to solve the wrong problems, you are only digging yourself deeper into a hole. As I grew closer and closer to what would be the end, I blamed external forces. I told my wife and my close friends that market conditions had hurt me, that cutting-edge tech was the problem, that blah blah blah.\"},void 0,!1,{fileName:\"/Users/polluterofminds/Development/tailwind-nextjs-starter-blog/_mdx_bundler_entry_point-e5188e79-a369-42dd-b423-d109b2bcb5b7.mdx\",lineNumber:11,columnNumber:1},this),(0,m.jsxDEV)(i.p,{children:\"I was the problem, and that's ok. Every founder is the main problem their company faces. Those problems, though, can be turned into successes by accepting responsibility, changing course, and making sound decisions. Not many companies do this, not many founders do this. And that's why so many companies fail. Graphite's failure was not the result of any external forces beyond my control. It was squarely within my control, but I failed to execute.\"},void 0,!1,{fileName:\"/Users/polluterofminds/Development/tailwind-nextjs-starter-blog/_mdx_bundler_entry_point-e5188e79-a369-42dd-b423-d109b2bcb5b7.mdx\",lineNumber:13,columnNumber:1},this),(0,m.jsxDEV)(i.p,{children:\"I won't enumerate the decisions I would revisit if given the opportunity\\u2014that's for another post. Instead, I will use this post to illustrate to other founders that while it is easy to blame something else, someone else, the success and failure of your company is fully under your control. Are there times where a founder literally can't do anything to fix things? Sure, but those are rare. Much rarer than founder interviews would have you believe.\"},void 0,!1,{fileName:\"/Users/polluterofminds/Development/tailwind-nextjs-starter-blog/_mdx_bundler_entry_point-e5188e79-a369-42dd-b423-d109b2bcb5b7.mdx\",lineNumber:15,columnNumber:1},this),(0,m.jsxDEV)(i.p,{children:\"There is nothing wrong with making bad decisions, even if those bad decisions lead to the end of your company. Nothing wrong, unless of course, you don't learn from those bad decisions. Your failure is your fault, but it is also your opportunity. The opportunity to learn from failure is huge, and not recognizing it, not grasping it, squeezing every bit of knowledge you can out of it, is the true failure.\"},void 0,!1,{fileName:\"/Users/polluterofminds/Development/tailwind-nextjs-starter-blog/_mdx_bundler_entry_point-e5188e79-a369-42dd-b423-d109b2bcb5b7.mdx\",lineNumber:17,columnNumber:1},this),(0,m.jsxDEV)(i.p,{children:\"Just remember, don't strive for failure. Strive to learn, knowing that failure is always a possibility. Don't hide from failure, don't find shame in it. Learn, adapt, move on. But acknowledge it.\"},void 0,!1,{fileName:\"/Users/polluterofminds/Development/tailwind-nextjs-starter-blog/_mdx_bundler_entry_point-e5188e79-a369-42dd-b423-d109b2bcb5b7.mdx\",lineNumber:19,columnNumber:1},this)]},void 0,!0,{fileName:\"/Users/polluterofminds/Development/tailwind-nextjs-starter-blog/_mdx_bundler_entry_point-e5188e79-a369-42dd-b423-d109b2bcb5b7.mdx\",lineNumber:1,columnNumber:1},this)}function pr(l={}){let{wrapper:i}=l.components||{};return i?(0,m.jsxDEV)(i,Object.assign({},l,{children:(0,m.jsxDEV)(je,l,void 0,!1,{fileName:\"/Users/polluterofminds/Development/tailwind-nextjs-starter-blog/_mdx_bundler_entry_point-e5188e79-a369-42dd-b423-d109b2bcb5b7.mdx\"},this)}),void 0,!1,{fileName:\"/Users/polluterofminds/Development/tailwind-nextjs-starter-blog/_mdx_bundler_entry_point-e5188e79-a369-42dd-b423-d109b2bcb5b7.mdx\"},this):je(l)}var gr=pr;return hr(yr);})();\n/*! Bundled license information:\n\nreact/cjs/react-jsx-dev-runtime.development.js:\n  (**\n   * @license React\n   * react-jsx-dev-runtime.development.js\n   *\n   * Copyright (c) Facebook, Inc. and its affiliates.\n   *\n   * This source code is licensed under the MIT license found in the\n   * LICENSE file in the root directory of this source tree.\n   *)\n*/\n;return Component;"
  },
  "_id": "blog/your-failure-is-your-fault.mdx",
  "_raw": {
    "sourceFilePath": "blog/your-failure-is-your-fault.mdx",
    "sourceFileName": "your-failure-is-your-fault.mdx",
    "sourceFileDir": "blog",
    "contentType": "mdx",
    "flattenedPath": "blog/your-failure-is-your-fault"
  },
  "type": "Blog",
  "readingTime": {
    "text": "3 min read",
    "minutes": 2.075,
    "time": 124500,
    "words": 415
  },
  "slug": "your-failure-is-your-fault",
  "path": "blog/your-failure-is-your-fault",
  "filePath": "blog/your-failure-is-your-fault.mdx",
  "toc": [],
  "structuredData": {
    "@context": "https://schema.org",
    "@type": "BlogPosting",
    "headline": "Your Failure is Your Fault",
    "datePublished": "2020-07-27T11:29:03.000Z",
    "dateModified": "2020-07-27T11:29:03.000Z",
    "description": "",
    "image": "/static/images/twitter-card.png",
    "url": "https://polluterofminds.com/blog/your-failure-is-your-fault"
  }
}